---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

The following dashboard show the data from NYC restaurant grade, for Asian food in Manhattan

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(p8105.datasets)
```


```{r data}
data(rest_inspec)

attr(rest_inspec, 'spec') <- NULL

rest_inspec = 
  rest_inspec %>% 
  separate_wider_delim(grade_date, "-", names = c("year", "month", "date")) %>%
  mutate(year = as.numeric(year)) %>% 
  select(-building, -camis, -dba, -phone, -inspection_date, -record_date, -street, -violation_code, -month, -date) %>% 
  drop_na() 
```
 
Column {data-width=450}
-----------------------------------------------------------------------

### Asian Food Inspection Grade in Manhattan

```{r chart 1}
rest_inspec %>% 
  filter (boro == "MANHATTAN", cuisine_description %in% c("Afghan", "Asian", "Bangladeshi", "Chinese/Japanese", "Chinese", "Japanese", "Indonesian", "Pakistani", "Filipino", "Indian", "Korean", "Pakistani", "Thai", "Vietnamese/Cambodian/Malaysia")) %>% 
  count(grade) %>% 
  mutate(grade = forcats::fct_relevel(grade, c("A", "B", "C", "Z", "P", "Not Yet Graded"))) %>% 
  plot_ly(x = ~grade, y = ~n, color = ~grade, type = "bar", colors = "viridis") %>% 
  layout(showlegend = FALSE)
```

### Score of Asian Food in Manhattan

```{r chart 2}
rest_inspec %>% 
  filter (boro == "MANHATTAN", cuisine_description %in% c("Afghan", "Asian", "Bangladeshi", "Chinese/Japanese", "Chinese", "Japanese", "Indonesian", "Pakistani", "Filipino", "Indian", "Korean", "Pakistani", "Thai", "Vietnamese/Cambodian/Malaysia")) %>% 
  plot_ly(y = ~score, color = ~cuisine_description, type = "box", colors = "viridis") %>% 
  layout(showlegend = FALSE)
```

Column {data-width=550}
-----------------------------------------------------------------------

### Average score based on grading year

```{r chart 3}
rest_inspec %>% 
  filter (boro == "MANHATTAN", cuisine_description %in% c("Afghan", "Asian", "Bangladeshi", "Chinese/Japanese", "Chinese", "Japanese", "Indonesian", "Pakistani", "Filipino", "Indian", "Korean", "Pakistani", "Thai", "Vietnamese/Cambodian/Malaysia")) %>% 
  mutate(score = as.numeric(score))  %>%
  select(cuisine_description, year, score) %>% 
  group_by(year, cuisine_description) %>% 
  summarize(mean_score = mean(score, na.rm = TRUE)) %>%
#it doesn't group by properly
  plot_ly(x = ~year, y = ~mean_score, type = 'scatter', mode = 'lines+markers', color = ~cuisine_description, colors = 'viridis')
```

